# Use an official Python runtime as a parent image
FROM python:3.8

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app

# Install Django directly
RUN pip install Django==4.2.8

# Copy the current directory contents into the container at /app
COPY . .

# Expose the port that Django will run on
EXPOSE 8081

# Run Django when the container launches
CMD ["python", "manage.py", "runserver", "0.0.0.0:8081"]
