#ifndef PROJECT_DEFS_H
#define PROJECT_DEFS_H

#define MAX_ROUTES  20
#define MAX_STR_LENGTH 100
#define BUFFER_SIZE (1 << 20)

#define LOCALHOST "127.0.0.1"
#define HTTP_RESPONSE_BAD_REQUEST "HTTP/1 403"

#endif //PROJECT_DEFS_H
